version: "3"

includes:
  deploy: ./DeployTasks.yml
tasks:
  # local commands
  up:
    desc: Run local dev servers
    deps: [backend, frontend]

  backend:
    desc: Run Backend Server
    cmds:
      - python status_page.py -p 8000 -w 1 -r

  frontend:
    desc: Run Frontend Server
    cmds:
      - python -m http.server 8001
